# This is a basic workflow to help you get started with Actions

name: Desc

on: issue_comment

permissions:
  pull-requests: write

jobs:
  approved:
    runs-on: ubuntu-latest  
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.issue.html_url }}
          PR_APPROVE_BY: ${{ github.event.issue.user.login }}
        run: |
          gh pr edit $PR_URL --title 'Approved by: $PR_APPROVE_BY'
