# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened


jobs:
  addlabel:
    if:  startsWith(github.head_ref, 'named**')
    runs-on: ubuntu-latest
    steps:
      - env:
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit $PR_URL --add-label "named"
